spring:
  application:
    name: ${MANAGEMENT_SERVICE_HOST}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT_INNER}/${POSTGRES_DATABASE_NAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}

  liquibase:
    change-log: db/changelog/main/main-changelog.yml
    enabled: true

security:
  jwt:
    lifetime: ${JWT_LIFETIME}
card:
  lifetime: ${CARD_LIFETIME}
  pagination:
    size: 3

server:
  port: ${MANAGEMENT_SERVICE_PORT_INNER}